In [1]:
import torch

In [2]:
# 1. Data gathering
# 2. Data preprocessing
# 3. Feature engineering
# 4. Model training
# 5. Testing

In [3]:
## Dataset used

# https://www.kaggle.com/datasets/mirichoi0218/insurance

In [4]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.13/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.13/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.13/dist-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.13/dist-packages (from kaggle) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kaggle) (26.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kaggle) (6.33.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.13/dist-packages (from kaggle) (9.1.2)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.13/dist-packages (from bleach->kaggle) (0.6.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (5.11.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.13/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (3.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (2026.7.22)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.12.2)

In [5]:
import kagglehub

# Download latest version

path = kagglehub.dataset_download("mirichoi0218/insurance")
print(f"Path of dataset files: {path}")

Using Colab cache for faster access to the 'insurance' dataset.
Path of dataset files: /kaggle/input/insurance

In [6]:
import os
print(os.getcwd())

/content

In [7]:
import pandas as pd

In [8]:
os.listdir('/kaggle/input/insurance')

['insurance.csv']

In [9]:
df = pd.read_csv(os.path.join(path, 'insurance.csv'))

In [10]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [12]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [13]:
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [14]:
# Split dataset before encoding

train_df, test_df = train_test_split(df, test_size = 0.2, random_state = 42)

In [15]:
# Encode categorical variable

label_encoder = {}
for col in ['sex', 'smoker', 'region']:
  le = LabelEncoder()
  train_df[col] = le.fit_transform(train_df[col])
  test_df[col] = le.transform(test_df[col])
  label_encoder[col] = le

In [16]:
# Features and target

X_train = train_df.drop(columns = ["charges"])
Y_train = train_df["charges"]
X_test = test_df.drop(columns = ["charges"])
Y_test = test_df["charges"]

In [17]:
print(X_train.head())

      age  sex    bmi  children  smoker  region
560    46    0  19.95         2       0       1
1285   47    0  24.32         0       0       0
1142   52    0  24.86         0       0       2
969    39    0  34.32         5       0       2
486    54    0  21.47         3       0       1

In [18]:
print(X_test.head())

      age  sex     bmi  children  smoker  region
764    45    0  25.175         2       0       0
887    36    0  30.020         0       0       1
890    64    0  26.885         0       1       1
1293   46    1  25.745         3       0       1
259    19    1  31.920         0       1       1

In [19]:
# Normalize features

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
# Print normalized training features array
print("Normalized X_train:")
print(X_train[:5])
print(f"\nShape: {X_train.shape}")

Normalized X_train:
[[ 0.47222651 -1.0246016  -1.75652513  0.73433626 -0.50874702 -0.45611589]
 [ 0.54331294 -1.0246016  -1.03308239 -0.91119211 -0.50874702 -1.35325561]
 [ 0.8987451  -1.0246016  -0.94368672 -0.91119211 -0.50874702  0.44102382]
 [-0.02537852 -1.0246016   0.62239299  3.20262882 -0.50874702  0.44102382]
 [ 1.04091797 -1.0246016  -1.50489287  1.55710045 -0.50874702 -0.45611589]]

Shape: (1070, 6)

In [21]:
# Convert to tensors

X_train_tensor = torch.tensor(X_train, dtype = torch.float32)
Y_train_tensor = torch.tensor(Y_train.values, dtype = torch.float32).view(-1,1)
X_test_tensor = torch.tensor(X_test, dtype = torch.float32)
Y_test_tensor = torch.tensor(Y_test.values, dtype = torch.float32).view(-1,1)

In [22]:
print(Y_train_tensor)
print(Y_train_tensor.shape)

tensor([[ 9193.8389],
        [ 8534.6719],
        [27117.9941],
        ...,
        [11931.1250],
        [46113.5117],
        [10214.6357]])
torch.Size([1070, 1])

In [23]:
# Define Neural Network

class SimpleNNRegressionModel(nn.Module):
  def __init__(self, input_dim):
    super(SimpleNNRegressionModel, self).__init__()
    self.network = nn.Sequential(
        nn.Linear(input_dim, 64),
        nn.ReLU(),
        nn.Linear(64,128),
        nn.ReLU(),
        nn.Linear(128, 1)
    )

  def forward(self,x):
    return self.network(x)

In [24]:
X_train_tensor.shape

torch.Size([1070, 6])

In [25]:
input_dim = X_train_tensor.shape[1]
model = SimpleNNRegressionModel(input_dim)

In [26]:
print(model)

SimpleNNRegressionModel(
  (network): Sequential(
    (0): Linear(in_features=6, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=128, bias=True)
    (3): ReLU()
    (4): Linear(in_features=128, out_features=1, bias=True)
  )
)

In [27]:
# Loss and Optimizer

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr = 0.01)

In [28]:
# Training Loop
epochs = 10000

for epoch in range(epochs):
  model.train()
  optimizer.zero_grad()
  predictions = model(X_train_tensor)
  loss = criterion(predictions, Y_train_tensor)
  loss.backward()

  optimizer.step()

  if (epoch + 1) % 100 == 0:
    print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

Epoch [100/10000], Loss: 44799356.0000
Epoch [200/10000], Loss: 31318246.0000
Epoch [300/10000], Loss: 28441818.0000
Epoch [400/10000], Loss: 26867218.0000
Epoch [500/10000], Loss: 25953024.0000
Epoch [600/10000], Loss: 25354654.0000
Epoch [700/10000], Loss: 24910990.0000
Epoch [800/10000], Loss: 24573392.0000
Epoch [900/10000], Loss: 24238728.0000
Epoch [1000/10000], Loss: 23836608.0000
Epoch [1100/10000], Loss: 23491586.0000
Epoch [1200/10000], Loss: 23185548.0000
Epoch [1300/10000], Loss: 22929928.0000
Epoch [1400/10000], Loss: 22724306.0000
Epoch [1500/10000], Loss: 22566522.0000
Epoch [1600/10000], Loss: 22390888.0000
Epoch [1700/10000], Loss: 22216904.0000
Epoch [1800/10000], Loss: 21943184.0000
Epoch [1900/10000], Loss: 21612606.0000
Epoch [2000/10000], Loss: 21375348.0000
Epoch [2100/10000], Loss: 21132936.0000
Epoch [2200/10000], Loss: 20744204.0000
Epoch [2300/10000], Loss: 20531248.0000
Epoch [2400/10000], Loss: 20315604.0000
Epoch [2500/10000], Loss: 20126738.0000
Epoch [2600/10000], Loss: 19899864.0000
Epoch [2700/10000], Loss: 19720464.0000
Epoch [2800/10000], Loss: 19521614.0000
Epoch [2900/10000], Loss: 19279746.0000
Epoch [3000/10000], Loss: 18917838.0000
Epoch [3100/10000], Loss: 18641624.0000
Epoch [3200/10000], Loss: 18093078.0000
Epoch [3300/10000], Loss: 17537616.0000
Epoch [3400/10000], Loss: 17149082.0000
Epoch [3500/10000], Loss: 16797406.0000
Epoch [3600/10000], Loss: 16410251.0000
Epoch [3700/10000], Loss: 16136001.0000
Epoch [3800/10000], Loss: 15847101.0000
Epoch [3900/10000], Loss: 15538187.0000
Epoch [4000/10000], Loss: 15277487.0000
Epoch [4100/10000], Loss: 15022941.0000
Epoch [4200/10000], Loss: 14665887.0000
Epoch [4300/10000], Loss: 14351177.0000
Epoch [4400/10000], Loss: 14059041.0000
Epoch [4500/10000], Loss: 13739906.0000
Epoch [4600/10000], Loss: 13444461.0000
Epoch [4700/10000], Loss: 13152277.0000
Epoch [4800/10000], Loss: 12891190.0000
Epoch [4900/10000], Loss: 12663396.0000
Epoch [5000/10000], Loss: 12430849.0000
Epoch [5100/10000], Loss: 12257396.0000
Epoch [5200/10000], Loss: 12083594.0000
Epoch [5300/10000], Loss: 11952438.0000
Epoch [5400/10000], Loss: 11846863.0000
Epoch [5500/10000], Loss: 11728961.0000
Epoch [5600/10000], Loss: 11529178.0000
Epoch [5700/10000], Loss: 11386864.0000
Epoch [5800/10000], Loss: 11284617.0000
Epoch [5900/10000], Loss: 11187689.0000
Epoch [6000/10000], Loss: 11104880.0000
Epoch [6100/10000], Loss: 11028136.0000
Epoch [6200/10000], Loss: 10965845.0000
Epoch [6300/10000], Loss: 10913914.0000
Epoch [6400/10000], Loss: 10850856.0000
Epoch [6500/10000], Loss: 10794439.0000
Epoch [6600/10000], Loss: 10737066.0000
Epoch [6700/10000], Loss: 10691288.0000
Epoch [6800/10000], Loss: 10648209.0000
Epoch [6900/10000], Loss: 10605913.0000
Epoch [7000/10000], Loss: 10565988.0000
Epoch [7100/10000], Loss: 10520729.0000
Epoch [7200/10000], Loss: 10492033.0000
Epoch [7300/10000], Loss: 10444686.0000
Epoch [7400/10000], Loss: 10398044.0000
Epoch [7500/10000], Loss: 10331002.0000
Epoch [7600/10000], Loss: 10285857.0000
Epoch [7700/10000], Loss: 10254890.0000
Epoch [7800/10000], Loss: 10210605.0000
Epoch [7900/10000], Loss: 10110653.0000
Epoch [8000/10000], Loss: 10034802.0000
Epoch [8100/10000], Loss: 9947799.0000
Epoch [8200/10000], Loss: 9887122.0000
Epoch [8300/10000], Loss: 9828398.0000
Epoch [8400/10000], Loss: 9766892.0000
Epoch [8500/10000], Loss: 9708350.0000
Epoch [8600/10000], Loss: 9666313.0000
Epoch [8700/10000], Loss: 9608947.0000
Epoch [8800/10000], Loss: 9563863.0000
Epoch [8900/10000], Loss: 9521925.0000
Epoch [9000/10000], Loss: 9488411.0000
Epoch [9100/10000], Loss: 9440397.0000
Epoch [9200/10000], Loss: 9411713.0000
Epoch [9300/10000], Loss: 9368783.0000
Epoch [9400/10000], Loss: 9340587.0000
Epoch [9500/10000], Loss: 9306800.0000
Epoch [9600/10000], Loss: 9279255.0000
Epoch [9700/10000], Loss: 9255241.0000
Epoch [9800/10000], Loss: 9222783.0000
Epoch [9900/10000], Loss: 9176106.0000
Epoch [10000/10000], Loss: 9136989.0000

In [29]:
# Model Evaluation

model.eval()
Y_pred = model(X_test_tensor).detach().numpy()

In [30]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error



Y_test_numpy = Y_test_tensor.numpy()


# Calculate metrics


mse = mean_squared_error(Y_test_numpy, Y_pred)
r2 = r2_score(Y_test_numpy, Y_pred)
rmse = mse ** 0.5
mae = mean_absolute_error(Y_test_numpy, Y_pred)

# Print the metrics
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R2) Score: {r2}")
print(f"Mean Absolute Error (MAE): {mae}")

Mean Squared Error (MSE): 34877424.0
Root Mean Squared Error (RMSE): 5905.7111341480295
R-squared (R2) Score: 0.7753448486328125
Mean Absolute Error (MAE): 3737.3232421875

In [31]:
def predict_charges(age, sex, bmi, children, smoker, region):
  # Assign the created DataFrame to input_data
  input_data = pd.DataFrame([[age, sex, bmi, children, smoker, region]],
                            columns = ["age", "sex", "bmi", "children", "smoker", "region"])

  # First encode all categorical columns
  for col in ["sex", "smoker", "region"]:
    input_data[col] = label_encoder[col].transform(input_data[col])

  # Scale the complete input data, convert to tensor, and predict outside the loop
  input_data_scaled = scaler.transform(input_data)
  input_data_tensor = torch.tensor(input_data_scaled, dtype = torch.float32)

  model.eval()
  with torch.no_grad():
    predicted_charge = model(input_data_tensor).item()
  return predicted_charge

In [32]:
predicted = predict_charges(19, 'female', 27.9, 0, 'yes', 'southwest')

In [33]:
# Print the predicted charge
print(f"Predicted insurance charge: ${predicted:,.2f}")

Predicted insurance charge: $19,134.93

1. Dataset(torch.utils.data.Dataset)
2. DataLoader(torch.utils.data.DataLoader)

In [34]:
# Creating our custom Dataset in Pytorch
# init() - initialised the dataset, load data, applied preprocessing
# len() - return the total numbers of samples in the dataset
# getitem() - Defines how to retrieve a single data sample when an index is provided

In [35]:
import torch
from torch.utils.data import Dataset, DataLoader

In [39]:
class InsuranceDataset(Dataset):
  def __init__(self, X, Y):
    self.X = X
    self.Y = Y

  def __len__(self):
      return len(self.X)

  def __getitem__(self, idx):
      features = torch.tensor(self.X[idx], dtype = torch.float32)
      target = torch.tensor(self.Y[idx], dtype = torch.float32)
      return features, target

In [44]:
dataset = InsuranceDataset(X_train, Y_train.values)

In [45]:
dataloader= DataLoader(dataset, batch_size = 32, shuffle = True)

In [47]:
for batch_idx, (features, targets) in enumerate(dataloader):
  print(f"Batch {batch_idx+1} :")
  print(f"Features: {features.shape}")
  print(f"Targets: {targets.shape}")
  break

Batch 1 :
Features: torch.Size([32, 6])
Targets: torch.Size([32])

In [ ]:
 # 1000 -> total number of data
 # batch-size -> 100
 # epoch -> 100

In [48]:
epochs = 10000

for epoch in range(epochs):
  model.train()
  for batch_idx,(batch_X, batch_Y) in enumerate(dataloader):

    print(f"Current batch: {batch_idx}")
    optimizer.zero_grad()
    predictions = model(X_train_tensor)
    loss = criterion(predictions, Y_train_tensor)
    loss.backward()
    optimizer.step()
    print(f"Batch [{batch_idx+1}/{epochs}], Loss: {loss.item():.4f}")

  if (epoch + 1) % 100 == 0:
    print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

Streaming output truncated to the last 5000 lines.
Batch [17/10000], Loss: 2164747.2500
Current batch: 17
Batch [18/10000], Loss: 2325191.2500
Current batch: 18
Batch [19/10000], Loss: 2518674.0000
Current batch: 19
Batch [20/10000], Loss: 2514345.7500
Current batch: 20
Batch [21/10000], Loss: 2416757.5000
Current batch: 21
Batch [22/10000], Loss: 2092697.6250
Current batch: 22
Batch [23/10000], Loss: 1723355.2500
Current batch: 23
Batch [24/10000], Loss: 1413382.7500
Current batch: 24
Batch [25/10000], Loss: 1291867.0000
Current batch: 25
Batch [26/10000], Loss: 1365032.5000
Current batch: 26
Batch [27/10000], Loss: 1541715.5000
Current batch: 27
Batch [28/10000], Loss: 1704961.6250
Current batch: 28
Batch [29/10000], Loss: 1750809.1250
Current batch: 29
Batch [30/10000], Loss: 1683039.2500
Current batch: 30
Batch [31/10000], Loss: 1522818.6250
Current batch: 31
Batch [32/10000], Loss: 1370795.8750
Current batch: 32
Batch [33/10000], Loss: 1293363.0000
Current batch: 33
Batch [34/10000], Loss: 1310327.7500
Current batch: 0
Batch [1/10000], Loss: 1386321.6250
Current batch: 1
Batch [2/10000], Loss: 1461777.2500
Current batch: 2
Batch [3/10000], Loss: 1494686.0000
Current batch: 3
Batch [4/10000], Loss: 1464952.6250
Current batch: 4
Batch [5/10000], Loss: 1399863.8750
Current batch: 5
Batch [6/10000], Loss: 1330191.6250
Current batch: 6
Batch [7/10000], Loss: 1291629.8750
Current batch: 7
Batch [8/10000], Loss: 1293963.8750
Current batch: 8
Batch [9/10000], Loss: 1324965.6250
Current batch: 9
Batch [10/10000], Loss: 1361125.8750
Current batch: 10
Batch [11/10000], Loss: 1379629.7500
Current batch: 11
Batch [12/10000], Loss: 1374020.0000
Current batch: 12
Batch [13/10000], Loss: 1347509.6250
Current batch: 13
Batch [14/10000], Loss: 1316227.0000
Current batch: 14
Batch [15/10000], Loss: 1293439.6250
Current batch: 15
Batch [16/10000], Loss: 1286708.1250
Current batch: 16
Batch [17/10000], Loss: 1294638.0000
Current batch: 17
Batch [18/10000], Loss: 1309792.5000
Current batch: 18
Batch [19/10000], Loss: 1323645.0000
Current batch: 19
Batch [20/10000], Loss: 1328862.8750
Current batch: 20
Batch [21/10000], Loss: 1325396.7500
Current batch: 21
Batch [22/10000], Loss: 1314161.7500
Current batch: 22
Batch [23/10000], Loss: 1300952.0000
Current batch: 23
Batch [24/10000], Loss: 1290898.1250
Current batch: 24
Batch [25/10000], Loss: 1286514.1250
Current batch: 25
Batch [26/10000], Loss: 1287569.8750
Current batch: 26
Batch [27/10000], Loss: 1292517.7500
Current batch: 27
Batch [28/10000], Loss: 1298242.1250
Current batch: 28
Batch [29/10000], Loss: 1301839.1250
Current batch: 29
Batch [30/10000], Loss: 1303330.3750
Current batch: 30
Batch [31/10000], Loss: 1301119.5000
Current batch: 31
Batch [32/10000], Loss: 1296958.7500
Current batch: 32
Batch [33/10000], Loss: 1292653.2500
Current batch: 33
Batch [34/10000], Loss: 1288751.6250
Current batch: 0
Batch [1/10000], Loss: 1286470.6250
Current batch: 1
Batch [2/10000], Loss: 1285811.8750
Current batch: 2
Batch [3/10000], Loss: 1286824.5000
Current batch: 3
Batch [4/10000], Loss: 1288438.3750
Current batch: 4
Batch [5/10000], Loss: 1290242.2500
Current batch: 5
Batch [6/10000], Loss: 1291539.7500
Current batch: 6
Batch [7/10000], Loss: 1292167.0000
Current batch: 7
Batch [8/10000], Loss: 1291820.7500
Current batch: 8
Batch [9/10000], Loss: 1291094.7500
Current batch: 9
Batch [10/10000], Loss: 1290310.2500
Current batch: 10
Batch [11/10000], Loss: 1289318.3750
Current batch: 11
Batch [12/10000], Loss: 1288163.3750
Current batch: 12
Batch [13/10000], Loss: 1287051.1250
Current batch: 13
Batch [14/10000], Loss: 1286496.7500
Current batch: 14
Batch [15/10000], Loss: 1286006.2500
Current batch: 15
Batch [16/10000], Loss: 1285674.7500
Current batch: 16
Batch [17/10000], Loss: 1285621.7500
Current batch: 17
Batch [18/10000], Loss: 1285573.2500
Current batch: 18
Batch [19/10000], Loss: 1285922.0000
Current batch: 19
Batch [20/10000], Loss: 1286158.8750
Current batch: 20
Batch [21/10000], Loss: 1286571.6250
Current batch: 21
Batch [22/10000], Loss: 1286889.2500
Current batch: 22
Batch [23/10000], Loss: 1287462.6250
Current batch: 23
Batch [24/10000], Loss: 1288039.8750
Current batch: 24
Batch [25/10000], Loss: 1288931.8750
Current batch: 25
Batch [26/10000], Loss: 1289097.2500
Current batch: 26
Batch [27/10000], Loss: 1290065.1250
Current batch: 27
Batch [28/10000], Loss: 1291008.7500
Current batch: 28
Batch [29/10000], Loss: 1291620.8750
Current batch: 29
Batch [30/10000], Loss: 1292384.0000
Current batch: 30
Batch [31/10000], Loss: 1292629.8750
Current batch: 31
Batch [32/10000], Loss: 1293827.7500
Current batch: 32
Batch [33/10000], Loss: 1294696.7500
Current batch: 33
Batch [34/10000], Loss: 1295469.7500
Current batch: 0
Batch [1/10000], Loss: 1296203.1250
Current batch: 1
Batch [2/10000], Loss: 1296794.6250
Current batch: 2
Batch [3/10000], Loss: 1297304.5000
Current batch: 3
Batch [4/10000], Loss: 1298413.8750
Current batch: 4
Batch [5/10000], Loss: 1299505.7500
Current batch: 5
Batch [6/10000], Loss: 1300059.1250
Current batch: 6
Batch [7/10000], Loss: 1300819.6250
Current batch: 7
Batch [8/10000], Loss: 1302843.1250
Current batch: 8
Batch [9/10000], Loss: 1304557.2500
Current batch: 9
Batch [10/10000], Loss: 1307034.3750
Current batch: 10
Batch [11/10000], Loss: 1309768.2500
Current batch: 11
Batch [12/10000], Loss: 1314230.0000
Current batch: 12
Batch [13/10000], Loss: 1318816.3750
Current batch: 13
Batch [14/10000], Loss: 1324852.3750
Current batch: 14
Batch [15/10000], Loss: 1331470.8750
Current batch: 15
Batch [16/10000], Loss: 1340939.3750
Current batch: 16
Batch [17/10000], Loss: 1349833.1250
Current batch: 17
Batch [18/10000], Loss: 1362985.8750
Current batch: 18
Batch [19/10000], Loss: 1376379.2500
Current batch: 19
Batch [20/10000], Loss: 1395964.3750
Current batch: 20
Batch [21/10000], Loss: 1414579.5000
Current batch: 21
Batch [22/10000], Loss: 1441172.0000
Current batch: 22
Batch [23/10000], Loss: 1463615.6250
Current batch: 23
Batch [24/10000], Loss: 1492338.1250
Current batch: 24
Batch [25/10000], Loss: 1512572.1250
Current batch: 25
Batch [26/10000], Loss: 1537240.6250
Current batch: 26
Batch [27/10000], Loss: 1547938.2500
Current batch: 27
Batch [28/10000], Loss: 1561456.7500
Current batch: 28
Batch [29/10000], Loss: 1557453.5000
Current batch: 29
Batch [30/10000], Loss: 1553689.7500
Current batch: 30
Batch [31/10000], Loss: 1528885.3750
Current batch: 31
Batch [32/10000], Loss: 1497644.3750
Current batch: 32
Batch [33/10000], Loss: 1453886.0000
Current batch: 33
Batch [34/10000], Loss: 1408547.5000
Current batch: 0
Batch [1/10000], Loss: 1364369.3750
Current batch: 1
Batch [2/10000], Loss: 1327771.8750
Current batch: 2
Batch [3/10000], Loss: 1301591.6250
Current batch: 3
Batch [4/10000], Loss: 1288521.0000
Current batch: 4
Batch [5/10000], Loss: 1286732.0000
Current batch: 5
Batch [6/10000], Loss: 1293311.2500
Current batch: 6
Batch [7/10000], Loss: 1305064.7500
Current batch: 7
Batch [8/10000], Loss: 1319626.2500
Current batch: 8
Batch [9/10000], Loss: 1335222.1250
Current batch: 9
Batch [10/10000], Loss: 1350051.7500
Current batch: 10
Batch [11/10000], Loss: 1365743.3750
Current batch: 11
Batch [12/10000], Loss: 1378082.1250
Current batch: 12
Batch [13/10000], Loss: 1391985.8750
Current batch: 13
Batch [14/10000], Loss: 1400488.1250
Current batch: 14
Batch [15/10000], Loss: 1409839.3750
Current batch: 15
Batch [16/10000], Loss: 1412964.2500
Current batch: 16
Batch [17/10000], Loss: 1414693.8750
Current batch: 17
Batch [18/10000], Loss: 1409945.3750
Current batch: 18
Batch [19/10000], Loss: 1402998.2500
Current batch: 19
Batch [20/10000], Loss: 1389514.8750
Current batch: 20
Batch [21/10000], Loss: 1375620.8750
Current batch: 21
Batch [22/10000], Loss: 1358226.1250
Current batch: 22
Batch [23/10000], Loss: 1342220.8750
Current batch: 23
Batch [24/10000], Loss: 1326875.8750
Current batch: 24
Batch [25/10000], Loss: 1313495.6250
Current batch: 25
Batch [26/10000], Loss: 1302599.3750
Current batch: 26
Batch [27/10000], Loss: 1294593.0000
Current batch: 27
Batch [28/10000], Loss: 1289464.5000
Current batch: 28
Batch [29/10000], Loss: 1286782.1250
Current batch: 29
Batch [30/10000], Loss: 1285883.7500
Current batch: 30
Batch [31/10000], Loss: 1286520.3750
Current batch: 31
Batch [32/10000], Loss: 1288449.5000
Current batch: 32
Batch [33/10000], Loss: 1291354.3750
Current batch: 33
Batch [34/10000], Loss: 1294373.5000
Current batch: 0
Batch [1/10000], Loss: 1298329.8750
Current batch: 1
Batch [2/10000], Loss: 1303757.2500
Current batch: 2
Batch [3/10000], Loss: 1310395.5000
Current batch: 3
Batch [4/10000], Loss: 1319716.5000
Current batch: 4
Batch [5/10000], Loss: 1330808.2500
Current batch: 5
Batch [6/10000], Loss: 1346250.6250
Current batch: 6
Batch [7/10000], Loss: 1364272.6250
Current batch: 7
Batch [8/10000], Loss: 1391836.1250
Current batch: 8
Batch [9/10000], Loss: 1423080.3750
Current batch: 9
Batch [10/10000], Loss: 1468724.2500
Current batch: 10
Batch [11/10000], Loss: 1517687.8750
Current batch: 11
Batch [12/10000], Loss: 1592179.5000
Current batch: 12
Batch [13/10000], Loss: 1664344.7500
Current batch: 13
Batch [14/10000], Loss: 1769860.1250
Current batch: 14
Batch [15/10000], Loss: 1855375.2500
Current batch: 15
Batch [16/10000], Loss: 1969810.6250
Current batch: 16
Batch [17/10000], Loss: 2018584.6250
Current batch: 17
Batch [18/10000], Loss: 2059489.8750
Current batch: 18
Batch [19/10000], Loss: 1989890.6250
Current batch: 19
Batch [20/10000], Loss: 1871417.0000
Current batch: 20
Batch [21/10000], Loss: 1678686.6250
Current batch: 21
Batch [22/10000], Loss: 1490744.0000
Current batch: 22
Batch [23/10000], Loss: 1349004.0000
Current batch: 23
Batch [24/10000], Loss: 1289934.0000
Current batch: 24
Batch [25/10000], Loss: 1310407.1250
Current batch: 25
Batch [26/10000], Loss: 1382242.7500
Current batch: 26
Batch [27/10000], Loss: 1466344.3750
Current batch: 27
Batch [28/10000], Loss: 1524341.2500
Current batch: 28
Batch [29/10000], Loss: 1546135.1250
Current batch: 29
Batch [30/10000], Loss: 1516524.2500
Current batch: 30
Batch [31/10000], Loss: 1460151.2500
Current batch: 31
Batch [32/10000], Loss: 1387961.2500
Current batch: 32
Batch [33/10000], Loss: 1327388.3750
Current batch: 33
Batch [34/10000], Loss: 1292522.2500
Current batch: 0
Batch [1/10000], Loss: 1288750.6250
Current batch: 1
Batch [2/10000], Loss: 1309070.7500
Current batch: 2
Batch [3/10000], Loss: 1339697.7500
Current batch: 3
Batch [4/10000], Loss: 1367808.2500
Current batch: 4
Batch [5/10000], Loss: 1382761.1250
Current batch: 5
Batch [6/10000], Loss: 1383135.3750
Current batch: 6
Batch [7/10000], Loss: 1366960.5000
Current batch: 7
Batch [8/10000], Loss: 1343749.1250
Current batch: 8
Batch [9/10000], Loss: 1318853.8750
Current batch: 9
Batch [10/10000], Loss: 1298870.5000
Current batch: 10
Batch [11/10000], Loss: 1287896.5000
Current batch: 11
Batch [12/10000], Loss: 1286637.2500
Current batch: 12
Batch [13/10000], Loss: 1292578.5000
Current batch: 13
Batch [14/10000], Loss: 1302165.7500
Current batch: 14
Batch [15/10000], Loss: 1312569.3750
Current batch: 15
Batch [16/10000], Loss: 1320168.0000
Current batch: 16
Batch [17/10000], Loss: 1323991.6250
Current batch: 17
Batch [18/10000], Loss: 1322787.6250
Current batch: 18
Batch [19/10000], Loss: 1319034.5000
Current batch: 19
Batch [20/10000], Loss: 1311626.3750
Current batch: 20
Batch [21/10000], Loss: 1303786.6250
Current batch: 21
Batch [22/10000], Loss: 1296206.2500
Current batch: 22
Batch [23/10000], Loss: 1290649.8750
Current batch: 23
Batch [24/10000], Loss: 1287158.2500
Current batch: 24
Batch [25/10000], Loss: 1285824.0000
Current batch: 25
Batch [26/10000], Loss: 1286467.2500
Current batch: 26
Batch [27/10000], Loss: 1287767.0000
Current batch: 27
Batch [28/10000], Loss: 1290606.3750
Current batch: 28
Batch [29/10000], Loss: 1293399.3750
Current batch: 29
Batch [30/10000], Loss: 1295911.1250
Current batch: 30
Batch [31/10000], Loss: 1298499.8750
Current batch: 31
Batch [32/10000], Loss: 1300553.5000
Current batch: 32
Batch [33/10000], Loss: 1301967.5000
Current batch: 33
Batch [34/10000], Loss: 1303106.2500
Current batch: 0
Batch [1/10000], Loss: 1302630.6250
Current batch: 1
Batch [2/10000], Loss: 1301789.2500
Current batch: 2
Batch [3/10000], Loss: 1300889.8750
Current batch: 3
Batch [4/10000], Loss: 1299672.1250
Current batch: 4
Batch [5/10000], Loss: 1298169.0000
Current batch: 5
Batch [6/10000], Loss: 1297089.1250
Current batch: 6
Batch [7/10000], Loss: 1295562.5000
Current batch: 7
Batch [8/10000], Loss: 1294797.0000
Current batch: 8
Batch [9/10000], Loss: 1293912.5000
Current batch: 9
Batch [10/10000], Loss: 1293549.1250
Current batch: 10
Batch [11/10000], Loss: 1293210.3750
Current batch: 11
Batch [12/10000], Loss: 1293594.5000
Current batch: 12
Batch [13/10000], Loss: 1293224.0000
Current batch: 13
Batch [14/10000], Loss: 1293692.1250
Current batch: 14
Batch [15/10000], Loss: 1294417.8750
Current batch: 15
Batch [16/10000], Loss: 1295313.8750
Current batch: 16
Batch [17/10000], Loss: 1296702.2500
Current batch: 17
Batch [18/10000], Loss: 1299212.3750
Current batch: 18
Batch [19/10000], Loss: 1302310.2500
Current batch: 19
Batch [20/10000], Loss: 1307022.2500
Current batch: 20
Batch [21/10000], Loss: 1312557.3750
Current batch: 21
Batch [22/10000], Loss: 1321474.3750
Current batch: 22
Batch [23/10000], Loss: 1332925.5000
Current batch: 23
Batch [24/10000], Loss: 1350015.1250
Current batch: 24
Batch [25/10000], Loss: 1369648.0000
Current batch: 25
Batch [26/10000], Loss: 1398514.8750
Current batch: 26
Batch [27/10000], Loss: 1430013.6250
Current batch: 27
Batch [28/10000], Loss: 1475929.0000
Current batch: 28
Batch [29/10000], Loss: 1523358.7500
Current batch: 29
Batch [30/10000], Loss: 1595706.6250
Current batch: 30
Batch [31/10000], Loss: 1662772.0000
Current batch: 31
Batch [32/10000], Loss: 1760346.3750
Current batch: 32
Batch [33/10000], Loss: 1832462.2500
Current batch: 33
Batch [34/10000], Loss: 1922792.0000
Current batch: 0
Batch [1/10000], Loss: 1948106.8750
Current batch: 1
Batch [2/10000], Loss: 1957627.8750
Current batch: 2
Batch [3/10000], Loss: 1875465.1250
Current batch: 3
Batch [4/10000], Loss: 1757121.0000
Current batch: 4
Batch [5/10000], Loss: 1591567.2500
Current batch: 5
Batch [6/10000], Loss: 1438331.5000
Current batch: 6
Batch [7/10000], Loss: 1329702.0000
Current batch: 7
Batch [8/10000], Loss: 1288407.3750
Current batch: 8
Batch [9/10000], Loss: 1309163.3750
Current batch: 9
Batch [10/10000], Loss: 1368990.3750
Current batch: 10
Batch [11/10000], Loss: 1438769.1250
Current batch: 11
Batch [12/10000], Loss: 1489163.1250
Current batch: 12
Batch [13/10000], Loss: 1513461.0000
Current batch: 13
Batch [14/10000], Loss: 1497298.6250
Current batch: 14
Batch [15/10000], Loss: 1458662.1250
Current batch: 15
Batch [16/10000], Loss: 1400643.7500
Current batch: 16
Batch [17/10000], Loss: 1345196.2500
Current batch: 17
Batch [18/10000], Loss: 1304535.8750
Current batch: 18
Batch [19/10000], Loss: 1287046.0000
Current batch: 19
Batch [20/10000], Loss: 1291809.8750
Current batch: 20
Batch [21/10000], Loss: 1310997.5000
Current batch: 21
Batch [22/10000], Loss: 1335496.6250
Current batch: 22
Batch [23/10000], Loss: 1355900.6250
Current batch: 23
Batch [24/10000], Loss: 1368705.7500
Current batch: 24
Batch [25/10000], Loss: 1368417.8750
Current batch: 25
Batch [26/10000], Loss: 1359821.6250
Current batch: 26
Batch [27/10000], Loss: 1342877.1250
Current batch: 27
Batch [28/10000], Loss: 1323888.8750
Current batch: 28
Batch [29/10000], Loss: 1305537.7500
Current batch: 29
Batch [30/10000], Loss: 1292734.1250
Current batch: 30
Batch [31/10000], Loss: 1286792.2500
Current batch: 31
Batch [32/10000], Loss: 1286799.6250
Current batch: 32
Batch [33/10000], Loss: 1290629.7500
Current batch: 33
Batch [34/10000], Loss: 1297258.5000
Current batch: 0
Batch [1/10000], Loss: 1304980.8750
Current batch: 1
Batch [2/10000], Loss: 1311467.1250
Current batch: 2
Batch [3/10000], Loss: 1316473.0000
Current batch: 3
Batch [4/10000], Loss: 1318790.2500
Current batch: 4
Batch [5/10000], Loss: 1319528.3750
Current batch: 5
Batch [6/10000], Loss: 1317454.3750
Current batch: 6
Batch [7/10000], Loss: 1314557.2500
Current batch: 7
Batch [8/10000], Loss: 1310031.1250
Current batch: 8
Batch [9/10000], Loss: 1304949.1250
Current batch: 9
Batch [10/10000], Loss: 1299808.1250
Current batch: 10
Batch [11/10000], Loss: 1295369.7500
Current batch: 11
Batch [12/10000], Loss: 1291516.1250
Current batch: 12
Batch [13/10000], Loss: 1288238.6250
Current batch: 13
Batch [14/10000], Loss: 1286325.3750
Current batch: 14
Batch [15/10000], Loss: 1285393.5000
Current batch: 15
Batch [16/10000], Loss: 1285044.8750
Current batch: 16
Batch [17/10000], Loss: 1285532.0000
Current batch: 17
Batch [18/10000], Loss: 1286053.1250
Current batch: 18
Batch [19/10000], Loss: 1286877.6250
Current batch: 19
Batch [20/10000], Loss: 1288106.2500
Current batch: 20
Batch [21/10000], Loss: 1289476.6250
Current batch: 21
Batch [22/10000], Loss: 1291374.1250
Current batch: 22
Batch [23/10000], Loss: 1293829.3750
Current batch: 23
Batch [24/10000], Loss: 1297023.8750
Current batch: 24
Batch [25/10000], Loss: 1300127.8750
Current batch: 25
Batch [26/10000], Loss: 1304633.1250
Current batch: 26
Batch [27/10000], Loss: 1310828.7500
Current batch: 27
Batch [28/10000], Loss: 1318462.7500
Current batch: 28
Batch [29/10000], Loss: 1326540.2500
Current batch: 29
Batch [30/10000], Loss: 1338918.0000
Current batch: 30
Batch [31/10000], Loss: 1352296.6250
Current batch: 31
Batch [32/10000], Loss: 1370405.0000
Current batch: 32
Batch [33/10000], Loss: 1389232.1250
Current batch: 33
Batch [34/10000], Loss: 1415584.0000
Current batch: 0
Batch [1/10000], Loss: 1440687.5000
Current batch: 1
Batch [2/10000], Loss: 1475241.3750
Current batch: 2
Batch [3/10000], Loss: 1505654.2500
Current batch: 3
Batch [4/10000], Loss: 1545185.5000
Current batch: 4
Batch [5/10000], Loss: 1575111.8750
Current batch: 5
Batch [6/10000], Loss: 1613252.0000
Current batch: 6
Batch [7/10000], Loss: 1630655.7500
Current batch: 7
Batch [8/10000], Loss: 1651574.8750
Current batch: 8
Batch [9/10000], Loss: 1643162.2500
Current batch: 9
Batch [10/10000], Loss: 1625816.6250
Current batch: 10
Batch [11/10000], Loss: 1576418.7500
Current batch: 11
Batch [12/10000], Loss: 1515915.3750
Current batch: 12
Batch [13/10000], Loss: 1443781.1250
Current batch: 13
Batch [14/10000], Loss: 1377540.1250
Current batch: 14
Batch [15/10000], Loss: 1325447.0000
Current batch: 15
Batch [16/10000], Loss: 1295023.8750
Current batch: 16
Batch [17/10000], Loss: 1286283.2500
Current batch: 17
Batch [18/10000], Loss: 1294302.3750
Current batch: 18
Batch [19/10000], Loss: 1312911.2500
Current batch: 19
Batch [20/10000], Loss: 1336433.8750
Current batch: 20
Batch [21/10000], Loss: 1360046.2500
Current batch: 21
Batch [22/10000], Loss: 1378930.0000
Current batch: 22
Batch [23/10000], Loss: 1395839.6250
Current batch: 23
Batch [24/10000], Loss: 1404096.2500
Current batch: 24
Batch [25/10000], Loss: 1409143.8750
Current batch: 25
Batch [26/10000], Loss: 1404070.1250
Current batch: 26
Batch [27/10000], Loss: 1393643.8750
Current batch: 27
Batch [28/10000], Loss: 1377024.5000
Current batch: 28
Batch [29/10000], Loss: 1357948.2500
Current batch: 29
Batch [30/10000], Loss: 1336722.8750
Current batch: 30
Batch [31/10000], Loss: 1318249.1250
Current batch: 31
Batch [32/10000], Loss: 1303049.3750
Current batch: 32
Batch [33/10000], Loss: 1292403.0000
Current batch: 33
Batch [34/10000], Loss: 1286554.8750
Current batch: 0
Batch [1/10000], Loss: 1285347.5000
Current batch: 1
Batch [2/10000], Loss: 1286928.2500
Current batch: 2
Batch [3/10000], Loss: 1290591.6250
Current batch: 3
Batch [4/10000], Loss: 1295602.5000
Current batch: 4
Batch [5/10000], Loss: 1301274.6250
Current batch: 5
Batch [6/10000], Loss: 1307891.2500
Current batch: 6
Batch [7/10000], Loss: 1313952.0000
Current batch: 7
Batch [8/10000], Loss: 1321504.0000
Current batch: 8